apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
configMapGenerator:
- files:
  - Corefile
  name: coredns
  namespace: kube-system
- files:
  - coredns.rego
  name: coredns-opa-policies
  namespace: kube-system
generatorOptions:
  disableNameSuffixHash: true
